version: "3.9"

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql:8.0
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "13306:3306"
    networks:
      - algafood-network

  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network

  algafood-api:
    image: hkprogrammer/algafood-api
    command: ["/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: development
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql

  algafood-proxy:
    build: ./nginx
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api


# docker build -t hkprogrammer/algafood-api --no-cache --build-arg JAR_FILE=algafood-api-0.0.1-SNAPSHOT.jar .
# docker-compose up
# 172.21.0.4